# Generated by Django 2.2.5 on 2021-10-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211019_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avartar',
            field=models.ImageField(blank=True, upload_to='avartar'),
        ),
    ]
